### ISSUE TITLE
The maximum length limit of %Library.Vector

### ISSUE THREAD

**Issue by ADAQIQI** [intersystems-community/vector-search-bugreports#1]
I noticed that the length of %Library.Vector does not specify a clear upper limit, but when I try to insert a particularly large embedded value (dimension 66000), the SQL statement will report an error. Is this related to my server configuration?

**Comment by bdeboe** [comment]
No, there is a limit of ~64000 elements for the underlying datatype, which is not meant to be configurable. We will add this to the documentation and consider a compile-time warning. Thanks for bringing this up!
